#!/bin/bash

folder='build'
if [ ! -d "$folder" ]; then
    echo "$folder older folder not found. Creating build folder ..."
    mkdir "$folder"
fi
cd "$folder"
echo "Building cmake ..."
cmake -DCMAKE_BUILD_TYPE=Debug ../
echo "Building make ..."
make
cd 'bin'
echo "executing assignment_02 ..."
./assignment_02
cd ../..
