#!/bin/bash

folder='build'
if [ ! -d "$folder" ]; then
    echo "$folder older folder not found. Creating build folder ..."
    mkdir "$folder"
fi
cd "$folder"
echo -e "\nBuilding cmake ..."
cmake -DCMAKE_BUILD_TYPE=Debug ../
echo -e "\nBuilding make ..."
make
cd 'bin'
echo -e "\nexecuting final_project ..."
./shadow_mapping
cd ../..
